name: prolab_unimet
description: "Project Manager website designed to administrate some resources and projects inside of the platform, the idea is to facilitate the creation, development and process inside of some Faculty labs."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  fl_chart: ^0.67.0
  firebase_auth: ^6.0.0
  provider: ^6.1.5
  firebase_core: ^4.1.1
  go_router: ^16.2.4
  cloud_firestore: ^6.0.2
  image_picker: ^1.0.4
  dio: ^5.7.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  pdf: ^3.10.7
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ProlabIcon.png
    - assets/
    
